package rs2321;

/*
 * rs2321.java
 *
 *
 */
import java.awt.event.ActionEvent;
import java.io.*;
import javax.swing.Timer;

/**
 *
 * @author Administrador
 */
public class rs2321 extends javax.swing.JFrame {

    pincel lienzo;
    WriterPort emisor;
    ReaderPort reader;
    String a = "", dato3, datomandado,dt1;
    int tiempo,ed, t, y,z,sc1=300, sc = 300, ac = 0, dx, dy, di;
     int h=300;
    char r;
    Timer reloj;
    boolean flag = true;

    /**
     * Creates new form rs2321
     */
    public rs2321() {



        initComponents();

        reloj = new Timer(4, (new java.awt.event.ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                // throw new UnsupportedOperationException("Not supported yet.");
                evento_reloj(e);
            }
        }));


        this.emisor = WriterPort.getInstance();
        this.reader = ReaderPort.getInstance();

        this.reader.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionEventPort actionEventPort = (ActionEventPort) evt;
                evento_de_Lectura(actionEventPort);
            }
        });

        lienzo = new pincel(this);                          //enlace a la clase pincel que es la que pinta
        lienzo.setBackground(new java.awt.Color(0, 0, 0));  //definicion de color de fondo
        panel1.add(lienzo);                                 //Agrega el canvas a un panel
        lienzo.setBounds(60, 20, 400, 301);


    }

    public void evento_de_Lectura(ActionEventPort actionEventPort) {

        a = a + actionEventPort.getReaded();

        ed = a.length();

        for (int i = 0; i < ed; i++) {

            r = a.charAt(i);
            if (r == '@') {
                z = i;

            } else if (r == '#') {
                
                caja1.setText(a);
                
                dato3 = a.substring(z + 1, i);
               
                
                
                sc1=sc = Integer.parseInt(dato3);
                caja4.setText(String.valueOf(sc));
                sc= 300 - sc;
                lienzo.trans(sc);
                a = "";
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja1 = new javax.swing.JTextField();
        caja4 = new javax.swing.JTextField();
        caja5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        star = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        cajahex = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cajahex1 = new javax.swing.JTextField();
        barra = new javax.swing.JScrollBar();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantilla Comunicación RS-232");
        getContentPane().setLayout(null);
        getContentPane().add(caja1);
        caja1.setBounds(50, 50, 160, 30);
        getContentPane().add(caja4);
        caja4.setBounds(140, 130, 100, 30);

        caja5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja5ActionPerformed(evt);
            }
        });
        getContentPane().add(caja5);
        caja5.setBounds(580, 100, 100, 30);

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(150, 170, 80, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 90, 340, 10);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recepcion  de Datos Puerto Serie");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 10, 330, 40);

        panel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel1.setLayout(null);
        getContentPane().add(panel1);
        panel1.setBounds(20, 230, 550, 340);

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(600, 240, 70, 30);

        jButton4.setText("Visualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(580, 280, 110, 30);

        jButton1.setText("Pintar Esfera");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(580, 320, 120, 23);

        star.setText("strar/stop");
        star.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                starActionPerformed(evt);
            }
        });
        getContentPane().add(star);
        star.setBounds(550, 20, 150, 60);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tiempo");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 90, 140, 20);

        jButton5.setText("Pintar Limite");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(570, 140, 120, 23);

        cajahex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajahexActionPerformed(evt);
            }
        });
        getContentPane().add(cajahex);
        cajahex.setBounds(610, 460, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Recepción Datos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 100, 140, 20);

        cajahex1.setText("0");
        cajahex1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cajahex1ActionPerformed(evt);
            }
        });
        getContentPane().add(cajahex1);
        cajahex1.setBounds(410, 120, 90, 30);

        barra.setMaximum(20);
        barra.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        barra.setVisibleAmount(5);
        barra.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barraAdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(barra);
        barra.setBounds(380, 150, 150, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Numero HEX");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(580, 440, 140, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-735)/2, (screenSize.height-631)/2, 735, 631);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed


        caja1.setText("");
        caja4.setText("");
       

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        lienzo.borrar(1);
        lienzo.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        int f = 0;

        if (f == 0) {
            panel1.setVisible(true);
            f = 1;
        } else {
            panel1.setVisible(false);
            f = 0;
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       

        dx = 0; //Integer.parseInt(cajax.getText());
        dy = 300; // Integer.parseInt(cajay.getText());
        di = 2; //Integer.parseInt(caja1.getText());

        
        h = Integer.parseInt(caja5.getText());
        

        lienzo.transferencia(dx, dy, di);
        lienzo.transfer(h);
        lienzo.repaint();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void starActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_starActionPerformed



        if (flag == true) {

            t = 1;
            reloj.start();
            flag = false;
        } else {

            flag = true;

            t = 0;
            reloj.stop();

        }

        lienzo.transferencia(t);

        lienzo.repaint();

        // TODO add your handling code here:
    }//GEN-LAST:event_starActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        h = Integer.parseInt(caja5.getText());
        lienzo.transfer(h);
         lienzo.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void cajahexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajahexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajahexActionPerformed

    private void cajahex1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cajahex1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cajahex1ActionPerformed

    private void barraAdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barraAdjustmentValueChanged
        
        tiempo = barra.getValue();
   cajahex1.setText(String.valueOf(tiempo));
    }//GEN-LAST:event_barraAdjustmentValueChanged

    private void caja5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja5ActionPerformed
    private void evento_reloj(java.awt.event.ActionEvent evt) {
  
   int hex=0,rest;
   String num="",num1="";
   
   hex=Integer.parseInt(dato3);
   if(hex==0){
       num="0";
   }else{
   while(hex!=0){
       rest=hex%16;
       hex=hex/16;
       
       if(rest==10){ 
         num1="A"; 
       }else if(rest==11){
         num1="B";  
       }else if(rest==12){
         num1="C";  
       }else if(rest==13){
         num1="D";  
       }else if(rest==14){
          num1="E"; 
       }else if(rest==15){
         num1="R";  
       }else {
         num1=String.valueOf(rest); 
       }
       num = num1 + num ;
   }
  }
cajahex.setText(num);
 if (sc1<h){
   dt1="B";   
  }else{
   dt1="A";   
  }     
 try {

           
            emisor.escribir("@"+dt1+","+tiempo+"#");
            datomandado = "@"+dt1+","+tiempo+"#";
         
        } catch (IOException iOException) {
        }




lienzo.transferencia(t);
        lienzo.repaint();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new rs2321().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar barra;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja4;
    private javax.swing.JTextField caja5;
    private javax.swing.JTextField cajahex;
    private javax.swing.JTextField cajahex1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel1;
    private javax.swing.JButton star;
    // End of variables declaration//GEN-END:variables
}
