package rs2321;

/*
 * rs2321.java
 *
 *
 */
import java.io.*;
import javax.swing.ImageIcon;

/**
 *
 * @author Administrador
 */
public class rs2321 extends javax.swing.JFrame {

    WriterPort emisor;
    ReaderPort reader;
    String a = "",datoh,datot;
    int ed,posi1,posi2,posi3,posi4;
    int limtemp=30,limhumed=50;
    char r;

    /**
     * Creates new form rs2321
     */
    public rs2321() {

        initComponents();

        this.emisor = WriterPort.getInstance();
        this.reader = ReaderPort.getInstance();

        this.reader.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionEventPort actionEventPort = (ActionEventPort) evt;
                evento_de_Lectura(actionEventPort);
            }
        });



    }

    public void evento_de_Lectura(ActionEventPort actionEventPort) {

        a = a + actionEventPort.getReaded();

        ed = a.length();

  for (int i = 0; i < ed; i++) {

            r = a.charAt(i);

            if (r == '#') {

                posi1=i;
                
            }else if (r == '%'){
                posi2=i;
            }else if (r == '@'){
                
                datoh = a.substring(posi1 + 1, posi2);
                datot = a.substring(posi2 + 1, i);
                
                caja1.setText(a);
                caja2.setText(datot);
                caja3.setText(datoh);
                
                a= "";
            }
           
  }
         if((Integer.parseInt(datot))>limtemp){
                indicador1.setText("OFF");
                
                imgcalen.setIcon(new ImageIcon(getClass().getResource("/imagen/rojo.png")));
            }else {
                indicador1.setText("ON");
                
                imgcalen.setIcon(new ImageIcon(getClass().getResource("/imagen/verde.png")));             
         }
         if((Integer.parseInt(datoh))>limhumed){
                indicador2.setText("ON");
                
                imgventi.setIcon(new ImageIcon(getClass().getResource("/imagen/roja.png")));
            }else {
                indicador2.setText("OFF");
                
                imgventi.setIcon(new ImageIcon(getClass().getResource("/imagen/verde.png")));             
         }
         
         try {

            String datomandado = "@" + limtemp + "%" + limhumed+ "#"; 
            emisor.escribir(datomandado);
           
        } catch (IOException iOException) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja1 = new javax.swing.JTextField();
        borrar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        caja2 = new javax.swing.JTextField();
        caja3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        imgcalen = new javax.swing.JLabel();
        imgventi = new javax.swing.JLabel();
        indicador1 = new javax.swing.JLabel();
        indicador2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        barra2 = new javax.swing.JScrollBar();
        barra1 = new javax.swing.JScrollBar();
        jLabel12 = new javax.swing.JLabel();
        indicador3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        indicador4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Plantilla Comunicación RS-232");
        getContentPane().setLayout(null);
        getContentPane().add(caja1);
        caja1.setBounds(30, 30, 160, 30);

        borrar.setText("Borrar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        getContentPane().add(borrar);
        borrar.setBounds(270, 20, 80, 30);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(30, 70, 340, 10);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("DATOS RECIBIDOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 10, 140, 18);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("%");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 280, 60, 20);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("IDEAL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(130, 370, 140, 18);
        getContentPane().add(caja2);
        caja2.setBounds(30, 110, 160, 30);
        getContentPane().add(caja3);
        caja3.setBounds(220, 110, 160, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("CALENTADOR ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 480, 140, 18);

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("CIRCULACION DE AIRE");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 480, 170, 18);

        imgcalen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rojo.jpg"))); // NOI18N
        getContentPane().add(imgcalen);
        imgcalen.setBounds(80, 510, 40, 40);

        imgventi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/rojo.jpg"))); // NOI18N
        getContentPane().add(imgventi);
        imgventi.setBounds(260, 510, 40, 40);

        indicador1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        getContentPane().add(indicador1);
        indicador1.setBounds(70, 560, 60, 30);

        indicador2.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 12)); // NOI18N
        getContentPane().add(indicador2);
        indicador2.setBounds(250, 560, 60, 30);

        jLabel7.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TEMPERATURA");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 90, 140, 18);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("HUMEDAD");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 90, 140, 18);

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("PARAMETROS DE LA EMCUBADORA");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 190, 320, 18);

        jLabel10.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 153));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("HUMEDAD");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 350, 140, 18);

        jLabel11.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("TEMPERATURA");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 220, 140, 18);

        barra2.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        barra2.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barra2AdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(barra2);
        barra2.setBounds(40, 430, 340, 20);

        barra1.setOrientation(javax.swing.JScrollBar.HORIZONTAL);
        barra1.addAdjustmentListener(new java.awt.event.AdjustmentListener() {
            public void adjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {
                barra1AdjustmentValueChanged(evt);
            }
        });
        getContentPane().add(barra1);
        barra1.setBounds(30, 300, 340, 20);

        jLabel12.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("IDEAL");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(130, 240, 140, 18);

        indicador3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        indicador3.setForeground(new java.awt.Color(0, 0, 153));
        indicador3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(indicador3);
        indicador3.setBounds(140, 280, 60, 20);

        jLabel14.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 153));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("%");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(200, 410, 60, 20);

        indicador4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        indicador4.setForeground(new java.awt.Color(0, 0, 153));
        indicador4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(indicador4);
        indicador4.setBounds(140, 410, 60, 20);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-417)/2, (screenSize.height-647)/2, 417, 647);
    }// </editor-fold>//GEN-END:initComponents

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed

        a = "";
       caja1.setText("");
       caja2.setText("");
       caja3.setText("");



    }//GEN-LAST:event_borrarActionPerformed

    private void barra1AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barra1AdjustmentValueChanged
     
        int valor = barra1.getValue();

        indicador3.setText(String.valueOf(valor));
        limtemp=valor;
        
        
    }//GEN-LAST:event_barra1AdjustmentValueChanged

    private void barra2AdjustmentValueChanged(java.awt.event.AdjustmentEvent evt) {//GEN-FIRST:event_barra2AdjustmentValueChanged
        
        int valor = barra2.getValue();

        indicador4.setText(String.valueOf(valor));
        limhumed=valor;
        
        
    }//GEN-LAST:event_barra2AdjustmentValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new rs2321().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollBar barra1;
    private javax.swing.JScrollBar barra2;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextField caja3;
    private javax.swing.JLabel imgcalen;
    private javax.swing.JLabel imgventi;
    private javax.swing.JLabel indicador1;
    private javax.swing.JLabel indicador2;
    private javax.swing.JLabel indicador3;
    private javax.swing.JLabel indicador4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
