/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JAIMEIDAI
 */
public class Relaciones extends javax.swing.JFrame {

    
    
    String r[]= new String[100];
    String r1[]= new String[100];
    String r2[]= new String[100];
    
    int n=0,b=0;
    /**
     * Creates new form Relaciones
     */
    public Relaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        caja1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        caja3 = new javax.swing.JTextArea();
        boton1 = new javax.swing.JButton();
        caja2 = new javax.swing.JTextField();
        boton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        caja4 = new javax.swing.JTextArea();
        boton3 = new javax.swing.JButton();
        caja5 = new javax.swing.JTextField();
        boton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        caja6 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        caja1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja1ActionPerformed(evt);
            }
        });

        caja3.setColumns(20);
        caja3.setRows(5);
        caja3.setText("Conjuntos de la \nRelacion Guardadas:");
        jScrollPane1.setViewportView(caja3);

        boton1.setText("Ingresar Conjunto");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        caja2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja2ActionPerformed(evt);
            }
        });

        boton2.setText("Calcular Propiedades");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        caja4.setColumns(20);
        caja4.setRows(5);
        caja4.setText("Propiedades:\n");
        jScrollPane2.setViewportView(caja4);

        boton3.setText("Borrar Todo");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        caja5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caja5ActionPerformed(evt);
            }
        });
        caja5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                caja5KeyPressed(evt);
            }
        });

        boton4.setText("ingresar el conjunto");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        caja6.setColumns(20);
        caja6.setRows(5);
        caja6.setText("Elementos del\nConjunto:");
        jScrollPane3.setViewportView(caja6);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RELACIONES PROPIEDADES");

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INGRESE CONJUNTO DE LA RELACIÓN");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 153));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("X");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Y");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jScrollPane1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(38, 38, 38))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(44, 44, 44)
                                    .addComponent(caja5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(boton4, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                .addComponent(boton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(196, 196, 196))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(caja5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boton3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caja1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(caja2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-405)/2, (screenSize.height-726)/2, 405, 726);
    }// </editor-fold>//GEN-END:initComponents

    private void caja1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja1ActionPerformed

    private void caja2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja2ActionPerformed

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        // TODO add your handling code here:
       String dato1,dato2;
       
       
       dato1=caja1.getText();
       dato2=caja2.getText();
       /*
       r[a]=dato1;
       a++;
       r[a]=dato2;
       a++;
       */
       r1[n]=dato1;
       r2[n]=dato2;
            //q=dato.charAt(n);
       // caja4.setText("Relaciones Guardadas");
        
  caja3.setText( caja3.getText()+"\n"+ "# Subconjunto "+String.valueOf(n+1)+"      "+"("+r1[n]+","+r2[n]+")") ;
        n++; 
        
        
     
    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed

        int m[][]= new int[b][b];
        int m1[][]= new int[b][b];
        int h=0,g=0,l1=0,l2=0,t1=0,t2=0,t3=0;
        
      for(int s=0; s<n;s++){
        for(int i=0;i<b;i++){
            for(int j=0;j<b;j++){
               
               if(((Integer.parseInt(r[i])) == (Integer.parseInt(r2[s])))&&((Integer.parseInt(r[j])) == (Integer.parseInt(r1[s])))){
                    
                    m[i][j]=1;
                    
                    //caja4.setText(caja4.getText()+"\n"+"iguales");  
                    break;
                }
             
            }
           
        }
      }
      caja4.setText("Propiedades:"+"\n");
        for(int i=0;i<b;i++){
            for(int s=0;s<b;s++){
                if ( m[i][s]!= 1){
                     m[i][s]=0;
                     l1++;
                }
                caja4.setText(caja4.getText()+String.valueOf(m[i][s]));
            }
            caja4.setText(caja4.getText()+"\n");
            if(i>0){
                if(m[b-i][b-i]==1){
                   h++;
             //  }
            }
            }
        }
        caja4.setText(caja4.getText()+"\n");
        
        
        
        for(int i=0;i<b;i++){
           for(int j=0;j<b;j++){
               for(int s=0;s<b;s++){
               
                   m1[i][j] += m[i][s]*m[s][j];
               }
               
             if(m[i][j] == m[j][i]){
                   g++;
              }
                if ( m1[i][j]==0){
                     l2++;
                }
           caja4.setText(caja4.getText()+String.valueOf(m1[i][j]));
            }
            caja4.setText(caja4.getText()+"\n");
        }
        caja4.setText(caja4.getText()+"\n");
      /*  
       for(int i=0;i<b;i++){
           for(int s=0;s<b;s++){
               if(m[i][s] == m[s][i]){
                   g++;
              }
                if ( m1[i][s]==0){
                     l2++;
                }
            caja4.setText(caja4.getText()+String.valueOf(m1[i][s]));
            }
            caja4.setText(caja4.getText()+"\n");
        }
       
       */ 
         
     // caja4.setText(caja4.getText()+" l1="+l1+"  l2="+l2+"\n");
        if(h==(b-1)){
            caja4.setText(caja4.getText()+"Reflexiva"+"\n");
            t1=1;
        }else{
         caja4.setText(caja4.getText()+"NO Reflexiva"+"\n");
        }
        if(g==((b)*(b))){
           caja4.setText(caja4.getText()+"Simetrica"+"\n");
           t2=1;
        }else{
        caja4.setText(caja4.getText()+"Antisimetrica"+"\n");
        }
        if(l1==l2){
           caja4.setText(caja4.getText()+"Transitiva"+"\n");
           t3=1;
        }else{
        caja4.setText(caja4.getText()+"No es Transitiva"+"\n");
        }
        
        if((t1==1)&&(t2==0)&&(t3==1)){
            caja4.setText(caja4.getText()+"Relación de orden Parcial"+"\n");
        }else {
            caja4.setText(caja4.getText()+"No es Relación de orden Parcial"+"\n");
        }
        
        if((t1==1)&&(t2==1)&&(t3==1)){
            caja4.setText(caja4.getText()+"Relación de orden Total"+"\n");
        }else {
            caja4.setText(caja4.getText()+"No es Relación de orden Total"+"\n");
        }
        
        if((t1==1)&&(t2==1)&&(t3==1)){
            caja4.setText(caja4.getText()+"Relación Equivalente"+"\n");
        }else {
            caja4.setText(caja4.getText()+"Relación No Equivalente"+"\n");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
      
        for(int i=0;i<n;i++){
            r1[i]="";
            r2[i]="";
        }
        n=0;
        b=0;
        caja1.setText("");
        caja2.setText("");
        caja3.setText("Conjuntos de la"+"\n"+"Relacion Guardadas:");
        caja4.setText("Propiedades:"+"\n");
        caja5.setText("");
        caja6.setText("Elementos del"+"\n"+"Conjunto:");
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_boton3ActionPerformed

    private void caja5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caja5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caja5ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
       
        
        r[b]=caja5.getText();
        caja5.setText("");
        
        caja6.setText(caja6.getText()+"\n"+r[b]);   
        
        b++;
        // TODO add your handling code here:
    }//GEN-LAST:event_boton4ActionPerformed

    private void caja5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caja5KeyPressed

      int t = evt.getKeyCode();

        if (t == evt.VK_ENTER) {
        
        r[b]=caja5.getText();
        caja5.setText("");
        caja6.setText(caja6.getText()+"\n"+r[b]);   
        b++;
            
        }   
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_caja5KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Relaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Relaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Relaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Relaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Relaciones().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JTextField caja1;
    private javax.swing.JTextField caja2;
    private javax.swing.JTextArea caja3;
    private javax.swing.JTextArea caja4;
    private javax.swing.JTextField caja5;
    private javax.swing.JTextArea caja6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
