/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * archivos.java
 *
 * 
 */
import java.io.*;


/**
 *
 * @author WOLF
 */
public class archivos extends javax.swing.JFrame {


File f;
FileReader LectorArchivo;
FileWriter EscritorArchivo;




    /** Creates new form archivos */
    public archivos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        boton_sel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Area1 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area2 = new javax.swing.JTextArea();
        boton_crearArch = new javax.swing.JButton();
        boton_Limpiar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Lectura de un Archivo");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(360, 30, 230, 30);

        boton_sel.setText("Seleccionar");
        boton_sel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_selActionPerformed(evt);
            }
        });
        getContentPane().add(boton_sel);
        boton_sel.setBounds(420, 80, 110, 23);

        Area1.setColumns(20);
        Area1.setRows(5);
        jScrollPane1.setViewportView(Area1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(340, 120, 240, 190);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Creación de un Archivo");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 30, 230, 30);

        Area2.setColumns(20);
        Area2.setRows(5);
        Area2.setToolTipText("Información a almacenar");
        jScrollPane2.setViewportView(Area2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(40, 100, 230, 120);

        boton_crearArch.setText("Crear");
        boton_crearArch.setToolTipText("Primero coloca la información y luego selecciona la ruta de destino");
        boton_crearArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_crearArchActionPerformed(evt);
            }
        });
        getContentPane().add(boton_crearArch);
        boton_crearArch.setBounds(60, 250, 70, 30);

        boton_Limpiar.setText("Limpiar");
        boton_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_LimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(boton_Limpiar);
        boton_Limpiar.setBounds(180, 250, 80, 30);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(300, 70, 10, 250);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-646)/2, (screenSize.height-365)/2, 646, 365);
    }// </editor-fold>//GEN-END:initComponents

    private void boton_selActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_selActionPerformed

        String informacion = this.Lectura_Archivo();

        Area1.setText(informacion);

        



    }//GEN-LAST:event_boton_selActionPerformed

    private void boton_crearArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_crearArchActionPerformed

      
       String datos = Area2.getText();

       this.Crear_archivo(datos);


    }//GEN-LAST:event_boton_crearArchActionPerformed

    private void boton_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_LimpiarActionPerformed


        Area2.setText("");
        Area1.setText("");

        
    }//GEN-LAST:event_boton_LimpiarActionPerformed


    public String Lectura_Archivo(){

        String info = "";
        String aux = "";

        javax.swing.JFileChooser jf1 = new javax.swing.JFileChooser();
        jf1.showOpenDialog(jf1);
        String path = jf1.getSelectedFile().getAbsolutePath();

        try {

            f = new File (path);
            LectorArchivo = new FileReader (f);
            BufferedReader BR = new BufferedReader (LectorArchivo);

            while (true){
                aux = BR.readLine();

                if (aux != null){
                    info = info + aux + "\n";
                }
                else{
                    break;
                }

            }
            BR.close();
            LectorArchivo.close();
            return info;
        }
        catch (IOException e){
            return null;
        }

    }




    public void  Crear_archivo(String info){

        javax.swing.JFileChooser jF2= new javax.swing.JFileChooser();
        String ruta = "";
        try{
        if(jF2.showSaveDialog(null)==jF2.APPROVE_OPTION){
            ruta = jF2.getSelectedFile().getAbsolutePath();


            f = new File(ruta);
            EscritorArchivo = new FileWriter(f);
            BufferedWriter BW = new BufferedWriter (EscritorArchivo);

            PrintWriter salida = new PrintWriter(BW);

            salida.write(info + "\n");

            salida.close();
            BW.close();


            }
        }catch (Exception ex){
            ex.printStackTrace();
        }


       
        
}








    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new archivos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area1;
    private javax.swing.JTextArea Area2;
    private javax.swing.JButton boton_Limpiar;
    private javax.swing.JButton boton_crearArch;
    private javax.swing.JButton boton_sel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

}
